# Generated by Django 3.0.6 on 2020-05-13 21:24

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount_range', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('age_range', django.contrib.postgres.fields.ranges.IntegerRangeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('personal_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('born_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='confirmed', max_length=10)),
                ('rejection_reason', models.IntegerField(blank=True, choices=[(1, 'Заявка не подходит по сумме'), (2, 'Заемщик не подходит по возрасту'), (3, 'иин является ИП'), (4, 'Заемщик в черном списке')], null=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.User')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.Program')),
            ],
        ),
    ]
